http:
  routers:
    nora:
      rule: Host(`nora.shuainium.com`)
      entryPoints:
        - websecure
      service: nora
      middlewares:
        - upload-limit
      tls:
        certResolver: cloudflare
    menu:
      rule: Host(`menu.shuainium.com`)
      entryPoints:
        - websecure
      service: nora
      middlewares:
        - menu-root
        - upload-limit
      tls:
        certResolver: cloudflare

  services:
    nora:
      loadBalancer:
        servers:
          - url: http://nora:8080
  middlewares:
    menu-root:
      replacePathRegex:
        regex: "^/$"
        replacement: "/menu"
    upload-limit:
      buffering:
        maxRequestBodyBytes: 9437184
        memRequestBodyBytes: 1048576
