"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ChefHat, Clock3, CookingPot, ExternalLink, Eye, EyeOff, Heart, ImageOff, LogOut, Menu as MenuIcon, Minus, Moon, Plus, Refrigerator, Sparkles, Sun, ThumbsDown, X } from "lucide-react";
type Language = "zh" | "en";
type Ingredient = { itemId: string; nameZh: string; nameEn: string; amountValue: number; amountUnitZh: string; amountUnitEn: string; inventoryQuantity: number };
type Dish = { id: string; nameZh: string; nameEn: string; prepMinutes: number; cookMinutes: number; ingredients: Ingredient[]; stepsZh: string[]; stepsEn: string[]; useSoon: boolean; imageId: string | null; imageStatus: string; imageSource: string | null; imagePageUrl: string | null };
type State = { dishes: Dish[]; total: number; generating: boolean; generationId?: string };
const text = {
  zh: { title: "今晚吃什么", subtitle: "按家中现有食材，为两人准备", signIn: "今天吃什么？", password: "密码", enter: "进入菜单", generate: "生成今日菜单", more: "再来六道", generating: "正在准备新菜品…", prep: "准备", cook: "烹饪", min: "分钟", useSoon: "优先消耗", ingredients: "所需食材", method: "做法", close: "关闭", nora: "前往 Nora", logout: "退出", like: "喜欢这张图片", dislike: "换一张图片", source: "查看图片来源", last: "这是最后一张图片", empty: "菜单还没有准备好", imagePending: "图片准备中", showPassword: "显示密码", hidePassword: "隐藏密码", servings: "份数", cookThis: "做这道菜", confirmCook: "确认完成并扣除食材？", confirmDetail: "Nora 会按所选份数扣除库存，并保留可撤销的记录。", cancel: "取消", confirm: "确认扣除", cooked: "库存已更新，可在 Nora 中撤销。" },
  en: { title: "What to cook tonight", subtitle: "Prepared for two from what you have", signIn: "What's cooking?", password: "Password", enter: "Enter Menu", generate: "Generate today's menu", more: "Give me six more", generating: "Preparing new dishes…", prep: "Prep", cook: "Cook", min: "min", useSoon: "Use soon", ingredients: "Ingredients", method: "Method", close: "Close", nora: "Go to Nora", logout: "Sign out", like: "I like this image", dislike: "Show another image", source: "Go to image source", last: "This is the last image", empty: "Your menu is not ready yet", imagePending: "Image is being prepared", showPassword: "Show password", hidePassword: "Hide password", servings: "Servings", cookThis: "Cook this", confirmCook: "Finish cooking and deduct ingredients?", confirmDetail: "Nora will deduct inventory for the selected servings and keep an undoable audit record.", cancel: "Cancel", confirm: "Confirm deduction", cooked: "Inventory updated. You can undo it in Nora." },
} as const;
async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/menu/${path}`, { cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || "Request failed");
  return body;
}
export default function MenuPage() {
  const [language, setLanguage] = useState<Language>("zh"), [theme, setTheme] = useState("dark");
  const [auth, setAuth] = useState<boolean | null>(null), [password, setPassword] = useState(""), [showPassword, setShowPassword] = useState(false);
  const [state, setState] = useState<State>({ dishes: [], total: 0, generating: false }), [visible, setVisible] = useState(6);
  const [selected, setSelected] = useState<Dish | null>(null), [servings, setServings] = useState(2), [confirmCook, setConfirmCook] = useState(false), [feedback, setFeedback] = useState<string | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [preferenceDish, setPreferenceDish] = useState<string | null>(null);
  const sentinel = useRef<HTMLDivElement>(null), holdTimer = useRef<ReturnType<typeof setTimeout> | null>(null), t = text[language];
  const load = useCallback(async () => setState(await api<State>(`state?offset=0&limit=${Math.max(visible, 6)}`)), [visible]);
  useEffect(() => { const lang = localStorage.getItem("nora-menu-language"), mode = localStorage.getItem("nora-menu-theme"); if (lang === "zh" || lang === "en") setLanguage(lang); if (mode === "light") setTheme("light"); api<{ authenticated: boolean }>("auth").then((v) => setAuth(v.authenticated)).catch(() => setAuth(false)); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("nora-menu-theme", theme); }, [theme]);
  useEffect(() => { document.documentElement.lang = language === "zh" ? "zh-Hans" : "en"; localStorage.setItem("nora-menu-language", language); }, [language]);
  useEffect(() => { if (auth) load().catch((e) => setError(e.message)); }, [auth, load]);
  useEffect(() => { if (!auth || !state.generating) return; const timer = window.setInterval(() => load().catch(() => undefined), 12000); return () => clearInterval(timer); }, [auth, state.generating, load]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelected(null); setPreferenceDish(null); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && visible < state.total) setVisible((v) => Math.min(v + 6, state.total)); }, { rootMargin: "500px" }); observer.observe(node); return () => observer.disconnect(); }, [state.total, visible]);
  async function login(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { await api("login", { method: "POST", body: JSON.stringify({ password }) }); setPassword(""); setAuth(true); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function generate() { setBusy(true); setError(""); try { await api("generate", { method: "POST", body: "{}" }); setVisible(6); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function preference(dish: Dish, value: "like" | "dislike") { setPreferenceDish(null); setFeedback(null); try { const result = await api<{ lastImage: boolean }>("preference", { method: "POST", body: JSON.stringify({ dishId: dish.id, preference: value }) }); if (result.lastImage) setFeedback(t.last); await load(); } catch (e) { setError((e as Error).message); } }
  async function finishCooking() { if (!selected) return; setBusy(true); setError(""); try { await api("cook", { method: "POST", body: JSON.stringify({ dishId: selected.id, servings }) }); setConfirmCook(false); setSelected(null); setFeedback(t.cooked); await load(); } catch (e) { setConfirmCook(false); setError((e as Error).message); } finally { setBusy(false); } }
  const formatAmount = (ingredient: Ingredient) => `${Number((ingredient.amountValue * servings / 2).toFixed(2))} ${language === "zh" ? ingredient.amountUnitZh : ingredient.amountUnitEn}`;
  const scaledStep = (step: string, dish: Dish) => dish.ingredients.reduce((text, ingredient) => { const original = `${ingredient.amountValue} ${language === "zh" ? ingredient.amountUnitZh : ingredient.amountUnitEn}`; return text.replaceAll(original, formatAmount(ingredient)); }, step);
  const startHold = (id: string) => { holdTimer.current = setTimeout(() => setPreferenceDish(id), 550); }, cancelHold = () => { if (holdTimer.current) clearTimeout(holdTimer.current); };
  if (auth === null) return <main className="menu-auth"><ChefHat size={30} /></main>;
  if (!auth) return <main className="menu-auth"><form onSubmit={login} className="menu-login"><ChefHat size={32} /><h1>{t.signIn}</h1><label><span>{t.password}</span><div className="password-field"><input autoFocus type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /><button type="button" className="icon" onClick={() => setShowPassword((v) => !v)} title={showPassword ? t.hidePassword : t.showPassword}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label>{error && <p className="menu-error">{error}</p>}<button className="menu-primary" disabled={busy || !password}>{t.enter}</button></form></main>;
  return <div className="menu-page"><header className="menu-header"><div className="wordmark"><span className="brand-dot" />Menu</div><nav><a className="icon icon-link" href="https://nora.shuainium.com" title={t.nora}><Refrigerator size={19} /></a><button className="icon" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{theme === "dark" ? <Sun size={19} /> : <Moon size={19} />}</button><div className="language-toggle"><button aria-pressed={language === "zh"} onClick={() => setLanguage("zh")}>中</button><button aria-pressed={language === "en"} onClick={() => setLanguage("en")}>En</button></div><button className="icon" title={t.logout} onClick={async () => { await api("logout", { method: "POST", body: "{}" }); setAuth(false); }}><LogOut size={18} /></button></nav></header>
    <main className="menu-main"><section className="menu-hero"><div><p className="menu-kicker">NORA · PRIVATE TABLE</p><h1>{t.title}</h1><p>{t.subtitle}</p></div><MenuIcon size={25} /></section>{error && <div className="menu-alert">{error}</div>}
      {!state.dishes.length && <section className="menu-empty"><ChefHat size={28} /><p>{state.generating ? t.generating : t.empty}</p><button className="menu-primary" disabled={busy || state.generating} onClick={generate}><Sparkles size={17} />{t.generate}</button></section>}
      <section className="dish-grid">{state.dishes.slice(0, visible).map((dish) => <article className="dish-card" key={`${dish.id}-${dish.imageId || "none"}`}><div className="dish-photo" tabIndex={0} role="button" onClick={() => { setServings(2); setSelected(dish); }} onPointerDown={() => startHold(dish.id)} onPointerUp={cancelHold} onPointerLeave={cancelHold} onContextMenu={(e) => { e.preventDefault(); setPreferenceDish(dish.id); }}>{dish.imageId ? <img src={`/api/menu/image?id=${encodeURIComponent(dish.imageId)}`} alt={language === "zh" ? dish.nameZh : dish.nameEn} /> : <div className="dish-placeholder"><ImageOff size={23} /><span>{t.imagePending}</span></div>}{dish.useSoon && <span className="use-soon">{t.useSoon}</span>}{preferenceDish === dish.id && <div className="image-preferences" onClick={(e) => e.stopPropagation()}><button onClick={() => preference(dish, "like")}><Heart size={17} />{t.like}</button><button onClick={() => preference(dish, "dislike")}><ThumbsDown size={17} />{t.dislike}</button>{dish.imagePageUrl && <a href={dish.imagePageUrl} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer"><ExternalLink size={17} />{t.source}</a>}</div>}</div><button className="dish-body" onClick={() => { setServings(2); setSelected(dish); }}><h2>{language === "zh" ? dish.nameZh : dish.nameEn}</h2><div className="dish-times"><span><Clock3 />{t.prep} {dish.prepMinutes} {t.min}</span><span><Clock3 />{t.cook} {dish.cookMinutes} {t.min}</span></div></button></article>)}</section>
      {feedback && <p className="menu-feedback">{feedback}</p>}{!!state.dishes.length && <div className="menu-actions"><button className="menu-primary" disabled={busy || state.generating} onClick={() => visible < state.total ? setVisible((v) => v + 6) : generate()}><Sparkles size={17} />{state.generating ? t.generating : t.more}</button></div>}<div ref={sentinel} className="menu-sentinel" /></main>
    {selected && <div className="recipe-backdrop" onMouseDown={() => setSelected(null)}><section className="recipe-sheet" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}>{selected.imageId && <img className="recipe-photo" src={`/api/menu/image?id=${encodeURIComponent(selected.imageId)}`} alt="" />}<div className="recipe-content"><button className="icon recipe-close" title={t.close} onClick={() => setSelected(null)}><X /></button><p className="menu-kicker">NORA · MENU</p><h2>{language === "zh" ? selected.nameZh : selected.nameEn}</h2><div className="dish-times"><span><Clock3 />{t.prep} {selected.prepMinutes} {t.min}</span><span><Clock3 />{t.cook} {selected.cookMinutes} {t.min}</span></div><div className="serving-control"><span>{t.servings}</span><button className="icon" disabled={servings <= 1} onClick={() => setServings((v) => Math.max(1, v - 1))}><Minus /></button><strong>{servings}</strong><button className="icon" disabled={servings >= 12} onClick={() => setServings((v) => Math.min(12, v + 1))}><Plus /></button></div><h3>{t.ingredients}</h3><ul>{selected.ingredients.map((i) => <li key={i.itemId}><span>{language === "zh" ? i.nameZh : i.nameEn}</span><strong>{formatAmount(i)}</strong></li>)}</ul><h3>{t.method}</h3><ol>{(language === "zh" ? selected.stepsZh : selected.stepsEn).map((step, index) => <li key={index}>{scaledStep(step, selected)}</li>)}</ol><button className="menu-primary cook-this" onClick={() => setConfirmCook(true)}><CookingPot size={18} />{t.cookThis}</button></div></section></div>}
    {confirmCook && selected && <div className="confirm-backdrop"><section className="cook-confirm" role="alertdialog" aria-modal="true"><CookingPot size={25} /><h2>{t.confirmCook}</h2><p>{t.confirmDetail}</p><strong>{language === "zh" ? selected.nameZh : selected.nameEn} · {servings} {t.servings}</strong><div><button onClick={() => setConfirmCook(false)}>{t.cancel}</button><button className="menu-primary" disabled={busy} onClick={finishCooking}>{t.confirm}</button></div></section></div>}
  </div>;
}
